[package]
name = "logag"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = "0.8.9"
chrono = "0.4.44"
clap = "4.6.1"
duckdb = "1.10502.0"
fastembed = "5.17.2"
log = "0.4.29"
paris = { version = "1.5", features = ["timestamps"] }
rmcp = { version = "1.7", features = ["server", "transport-streamable-http-server"] }
schemars = "1.2.1"
serde = "1.0.228"
serde_json = "1.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "uuid", "chrono"] } 
sqlx-cli = "0.8.6"
tokio = { version="1.52.3", features=["full"] }
tokio-postgres = "0.7.17"
tokio-util = "0.7.18"
toml = "1.1.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.11", features = ["v4", "v7", "fast-rng"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
